Capstone branch
josuerushanika/capstone1 pull request #1
Opened 2023-01-12 14:24 UTC by josuerushanika

### In this capstone project I build an online website for a conference.

 I follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) to build my project:

I build only these 2 pages:

The home page.
The about page.
Each of these pages has versions for 2 different screen sizes:

Mobile: up to 768px wide.
Desktop: 768px or wider.

**Interactions  Links**
The home page  has a link in the menu to the about page.
The logo in the header links to the home page.
**Mobile menu**
When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
The mobile menu should have a close (X) button that closes the menu.
**Dynamic page**
The section "Featured speakers" I created dynamically in JavaScript.
I used a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

2023-01-13 00:04 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @josuerushanika 👋, 

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

### Project presentation

- 🏮Please kindly record a video describing your project.
- 🏮The maximum length of the video is 5 minutes.
- 🏮The video contains a clear and objective description of the project.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-13 00:04 UTC, abdulhamiid commented on index.html
> +     <div class="small-underline"></div>
Please kindly align the text `Speaker` to the center similar to the design in the template
![image](https://user-images.githubusercontent.com/78251927/212203866-77d9aba8-5f2b-4e7f-af10-026f736059fd.png)

Template
![image](https://user-images.githubusercontent.com/78251927/212203947-f1a1b38e-fb89-446c-972d-8015bc5e34dd.png)

2023-01-13 00:04 UTC, abdulhamiid commented on about.html
> +        <div class="tech-explain aboutpg">
Part of the content of this section is covered by the navbar, please kindly fix the issue in your styling 👍 

![image](https://user-images.githubusercontent.com/78251927/212204711-3e9ff209-12e9-4048-a826-17f290af202b.png)

2023-01-13 00:04 UTC, abdulhamiid commented on about.html
> +          </div>
Please kindly increase the width as the template and change the text color to white so that the text will be more readable 
![image](https://user-images.githubusercontent.com/78251927/212205033-2aeb62e4-c5ca-4503-95af-63fb42d3ce25.png)

Template
![image](https://user-images.githubusercontent.com/78251927/212205135-50096e00-6425-4caf-a9a8-74cf21796631.png)

2023-01-13 00:04 UTC, abdulhamiid commented on index.html
> +      </ul>
As part of the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md), the pages should look almost identical to the original design

![image](https://user-images.githubusercontent.com/78251927/212205424-3ccb7954-3ee8-4ae5-bafe-6207741b2ff3.png)

Template
![image](https://user-images.githubusercontent.com/78251927/212205631-a7dedfec-3cb1-4490-9613-61b3ba17636f.png)

Please kindly add some` margin/padding` to add more spaces to the nav list items 

Kindly implement this in both the `Home` and `About` pages `Nav`

2023-01-13 00:04 UTC, abdulhamiid commented on main.js
> +}
Good job implementing the "More" button on the home page to toggle the `Speakers` display 👍

2023-01-13 07:53 UTC, josuerushanika commented on index.html
> +     <div class="small-underline"></div>
It's fixed

2023-01-13 08:04 UTC, josuerushanika commented on about.html
> +        <div class="tech-explain aboutpg">
It's fixed

2023-01-13 08:41 UTC, josuerushanika commented on about.html
> +          </div>
Thanks it is fixed

2023-01-13 16:02 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ ✔️ 🎉 

Hi @josuerushanika, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history 👍 
- [ ] Nice design 👍 

## Optional suggestions

- [OPTIONAL] As recommended in the project, you should record a video that contains a highlight about a piece of code that you find interesting or proud of making, also I think it can be more useful to be more confident when you present your project 😉 😉. I mention this requirement as optional because the previous reviewer misses it so next time, make sure you meet all the requirements for the project presentation🙃 🙃 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 16:13 UTC, merged

2023-07-28 22:18 UTC, josuerushanika commented
Thank You